### ISSUE TITLE
Add MPRIS thumbs up/down actions

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#204]
A feedback from Artem Hluvchynskyi (Nuvola Patron):

> Which feature are you missing in Nuvola Player most? -- [...] "thumbs up/down" buttons available via MPRIS (mostly interested in GNOME Shell media extension)

Right now, I'm not sure how to do it because thumbs up/down actions are not in the [MPRIS specification](http://specifications.freedesktop.org/mpris-spec/latest/).

Tasks
- [x] xesam:userRating in Metadata property
- [x] API to set rating in Nuvola Player
- [x] PR to Media Player Indicator to add support for Nuvola's rating
- [x] Add documentation for web app developers
- [x] Add rating to Google Play Music script
- [x] Check extensions.gnome.org

**Comment by excieve** [comment]
It's possible to start with exposing `xesam:userRating` in [Metadata](http://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Metadata) property. It's not boolean, rather continuous 0.0 to 1.0 but may be mapped from a boolean thumbs up/down I think. Alternatively a custom element of the `Metadata` map (e.g. `nuvola:booleanUserRating`) may be introduced for this, then a client may use it directly if it supports this. This is probably cleaner but would require implementation on the client side. Both may be done in fact to allow graceful fallback.

Anyway, this will at least show if the track is "thumbed up" or not in order to know if it's fine to use a "thumbs up" key shortcut.

Then the interface may be extended to include the actions but it would require support on the other side too if feasible.

**Comment by fenryxo** [comment]
With the changes which has just landed, thumbs up/down is shown as five/one stars in the GNOME Shell Media Player extension. Will work further on a way to set rating from the extension.

**Comment by fenryxo** [comment]
Nuvola Player now contains MPRIS API to set rating - NuvolaSetRating method. PR to Media Player Indicator will follow.

**Comment by fenryxo** [comment]
PR to Media Player Indicator: eonpatapon/gnome-shell-extensions-mediaplayer#250

**Comment by excieve** [comment]
Thanks for your awesome work on this @fenryxo! Even just exposing the rating is very useful for me already.

**Comment by fenryxo** [comment]
Still no luck to get my PR eonpatapon/gnome-shell-extensions-mediaplayer#250 merged :-(

However, I'm going to work on implementation in the Google Play Music script this month. Rating should be shown in the upstream Media Player GNOME Shell extension, but you will have to use [my branch](https://github.com/fenryxo/gnome-shell-extensions-mediaplayer/tree/nuvola-rating) if you want to also set rating from the indicator.

**Comment by fenryxo** [comment]
Google Play Music script 5.13 with track rating has been released. Requires Nuvola Player 3.1 for this feature.

**Comment by fenryxo** [comment]
:tada: [My pull request](https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/250) gas been merged upstream.
