### ISSUE TITLE
Feature Request: Auto open lyrics sidebar

### ISSUE THREAD

**Issue by Frozenfire92** [tiliado/nuvolaruntime#205]
It would be nice if there was a setting/toggle to open the lyrics sidebar automatically only if the currently playing song has lyrics found. If a song comes up that doesn't have lyrics the sidebar would close
##

**Comment by fenryxo** [comment]
Hello @Frozenfire92. Thanks for your idea how to make Nuvola Player better. I've added your feature request to [the wishlist](https://github.com/tiliado/nuvolaplayer/issues?q=is%3Aopen+label%3Awishlist+sort%3Acreated-asc) with a default low priority. Should you [become a Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/#donate), I will remove tag *postponed* and add tag *patron* to raise its priority.

Jiří Janoušek, Nuvola Player Developer • *My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).*

**Comment by murtezayesil** [comment]
**Is your feature request related to a problem? Please describe:**
I am so annoyed that I have to toggle sidebar everytime I want to read lyrics. I don't mind sidebar staying there even when no lyrics found for the current song.

A clear and concise description of what the problem is. Ex. I have an issue when ...
I have to do same thing every single time i launch an app.

**Describe the solution you'd like:**
A switch in settings that shows/hides sidebar on launch

A clear and concise description of what you want to happen. What are the benefits and drawbacks?
Benefits: I will love you more

**Describe alternatives you've considered:**
Not pay for subscription to read lyrics

A clear and concise description of any alternative solutions or features you've considered.
Listening to lyrics free songs 

**Additional context:**
I think "a switch in settings that shows/hides sidebar on launch" is clear enough.
Add any other context or screenshots about the feature request here.

**Comment by fenryxo** [comment]
Hello @murtezayesil. Thanks for your comment. Indeed, there are two annoying regressions: #515 and #516.

**Comment by fenryxo** [comment]
The feature is now publicly available in Nuvola 4.16.20-gaa3880c. Regressions #515 and #516 were fixed as well.

The documentation needs to be updated.

**Comment by fenryxo** [comment]
[Lyrics fetching documentation](https://nuvola.tiliado.eu/docs/4/lyrics.html) updated.
