### ISSUE TITLE
[regression] Unable to start nuvolaplayer3 stable on Kubuntu 17.04

### ISSUE THREAD

**Issue by joshuafcole** [tiliado/nuvolaruntime#351]
```
nuvolaplayer3: error while loading shared libraries: libunity.so.9: cannot open shared object file: No such file or directory
```

nuvolaplayer2 and previous worked fine. I certainly understand if certain functionality is missing, but it's unfortunate to be completely unable to use the software because of a DM choice, and even more so when previous major versions worked without issue cross-DM.

**Comment by fenryxo** [comment]
Hello @joshuafcole. Thanks for taking the time to report this issue. There seems to be a bug in packaging because the packages contain incomplete list of dependencies. You can install the `libunity9` package to fix the issue.

Note to self: Find out why `${shlibs:Depends}` expands only to libdiorite but other deps are missing.

**Comment by joshuafcole** [comment]
This seems to have fixed the issue, thank you for the prompt support!

**Comment by joshuafcole** [comment]
Will leave this issue open to track the underlying issue (unless you'd like to create a new issue # for it). Feel free to update the title appropriately.
