### ISSUE TITLE
Error installing new flatpack distribution - ConfigureRemote not allowed for user

### ISSUE THREAD

**Issue by scotte** [tiliado/nuvolaruntime#396]
I'm trying to install nuvolaplayer on a new laptop (the first time I've installed with the new flatpack packaging). This computer is running Ubuntu 17.10. I receive the following error:

error: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Flatpak system operation ConfigureRemote not allowed for user

Any ideas? Searches on the topic haven't helped, aside from suggesting it's related to polkit, but I've found no solution. Thanks.

**Comment by scotte** [comment]
Ah ha! I had to run:

```
flatpak install --user --from https://nuvola.tiliado.eu/eu.tiliado.Nuvola.flatpakref
```

I.e. with the --user flag, not mentioned on https://nuvola.tiliado.eu/nuvola/ubuntu/artful/ but perhaps required?

**Comment by fenryxo** [comment]
Hello @scotte. When you type `flatpak install --from https://nuvola.tiliado.eu/eu.tiliado.Nuvola.flatpakref`, the system should ask you for the administrator password. The only way I was able to reproduce the Access Denied error was when I canceled the password dialog.

Was the administrator password dialog shown in your case?

**Comment by scotte** [comment]
Administrator? This is *nix - do you mean root user? If so, no - I was not prompted for the root user passwd or sudo rights.

Honestly, I don't quite get the point of the new app - after running it, all it did was give me command line instructions to install the individual player apps, which is kind of annoying. I also didn't like that this is now a "free trial" - I guess there are plans to sell this as a product. Frankly, I just went back to the old 3.0 version that is packaged as debian packages - much easier to install via apt.

**Comment by fenryxo** [comment]
> Administrator? This is *nix - do you mean root user?

No, I meant administrator as in the screenshot below. Is there any user configured as administrator on your system?

![ubuntu_administrator](https://user-images.githubusercontent.com/853706/34466956-c470a270-eee4-11e7-908a-aee894b0754d.png)

> If so, no - I was not prompted for the root user passwd or sudo rights.

The following dialog is shown on a clean Ubuntu 17.10 installation. If it is not shown in your case, PolicyKit may be misconfigured on your system.

![ubuntu_policykit_dialog](https://user-images.githubusercontent.com/853706/34466988-834ce6fe-eee5-11e7-8f7c-d117989598d9.png)

> Honestly, I don't quite get the point of the new app - after running it, all it did was give me command line instructions to install the individual player apps, which is kind of annoying. 

The `eu.tiliado.Nuvola` flatpak contains only the runtime and a shared background service (for global keyboard shortcuts, media keys, HTTP remote control, and more). Then you need to install the scripts you want to use, which we cannot know in advance. DEB packages installed all scripts, which was a mistake because people complained that they had the list of apps polluted with streaming services they weren't interested in.

> I also didn't like that this is now a "free trial" - I guess there are plans to sell this as a product.

The genuine flatpak builds of Nuvola 4 are the product we are selling. The source code is still available free of charge under BSD license and there are third-party builds available based on it, so there are still several options for people who don't want to pay. Also, the free trial period is unlimited.

> Frankly, I just went back to the old 3.0 version that is packaged as debian packages - much easier to install via apt.

If Nuvola 3.0 works well for you, there is no need to upgrade.

Anyway, thanks for your feedback.

**Comment by scotte** [comment]
I don't have any of that cruft on my box - it's a debootstrap install with no gnome, unity, or any DE for that matter - just i3wm started with "startx" and the minimal set of packages I need and want.

Thanks for the response, I do appreciate it!

**Comment by fenryxo** [comment]
Then there might be a bug in flatpak packaging in Ubuntu. It should depend on PolicyKit or whatever is needed to get root rights. `sudo flatpak install ...` might also work but PolicyKit is preferred these days.

Anyway, there is probably nothing I can do with that. Please report an Ubuntu bug if you wish the issue to be resolved.
