### ISSUE TITLE
Fix or replace the free trial

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#422]
There are a few issues with the current implementation of the free trial.

1. Users don't like the idea of paying for Nuvola.
   
   Well, as @pszi1ard pointed out (https://github.com/tiliado/nuvolaruntime/issues/422#issuecomment-390324713), they don't like the idea of paying for OSS in general and the reasons are complex.
   
   I believe the genuine builds of Nuvola are worth paying. There is a lot of care and work behind them. There are continuous updates, new features and bug fixes are released as soon as possible. You don't have to wait half a year for new release fixing an annoying bug. Changes are announced in [Nuvola News blog](https://medium.com/nuvola-news). I used to do big release announcements to describe all changes at once, but I switched to micro-release announcements to describe the new goodies sooner. The price starts from a symbolic $1/month (with an annual payment to save payment processor fees). Users not willing to pay may download the entire source code for free or use third-party builds.

2. Users don't like the trial widget, some calling it "a nag bar". These banners are not liked in general. A similar bar in Nuvola 3, which asked for donations without any confusing wording, was neither favorite. A widget asking for purchase should not be in the main window or it is always annoying.  

3. Users are confused because the trial is not time-limited. Since the time limit was not implemented, the wording of the widget became ill-conceived and confusing.

Solution 1: Replace the free trial with a money-back guarantee
-------------------------------------------------------------------------------

### Implementation

- The free trial widget is removed from the main window.
- All features are locked.
- A "Purchase Nuvola Apps Runtime to unlock features" is placed above the list of features.
- Add a money-back guarantee to Gumroad offers.

### Advantages

- No trial bar in the main window.
- Easy to implement.
- Users still can check a basic functionality of the websites, e.g., whether they load, play music and let the user log in and perform other typical actions.
- Users get their money back if they are not satisfied with Nuvola.

### Disadvantages

- Users cannot check Nuvola Basic features before paying.

Solution 2: Add a time limit to the free trial
-----------------------------------------------------

### Implementation

- The free trial widget is removed from the main window.
- All features are locked.
- A "Connect Tiliado account to restore purchases or start a free trial" button is placed above the list of features.
- The free trial period is controlled server-side.
- If there is no membership, show "Start a N-day free trial" and "Purchase Nuvola Apps Runtime" buttons.
- If the trial has expired, show a "Purchase Nuvola Apps Runtime to unlock features" button.

### Advantages

- No trial bar in the main window.
- Users can check a basic functionality of the websites, e.g., whether they load, play music and let the user log in and perform other typical actions.
- Users can check Nuvola Basic features before paying.

### Disadvantages

- More complicated to implement.
- Users cannot check Nuvola Basic features before connecting a Tiliado account.

Solution 3: Combine solutions 2 & 3
---------------------------------------------

### Advantages

- No trial bar in the main window.
- Users can check a basic functionality of the websites, e.g., whether they load, play music and let the user log in and perform other typical actions.
- Users can check Nuvola Basic features before paying.
- Even after paying, users can get their money back if they are not satisfied with Nuvola.

### Disadvantages

- More complicated to implement.
- Users cannot check Nuvola Basic features before connecting a Tiliado account.

Draft of Announcement
----------------------------

### Common

Before the free trial was introduced, **Nuvola 4.x** was a premium rolling series for Nuvola Premium/Patron users. Therefore, it required a $3+/month subscription, or it wouldn’t run at all. An obsolete and not-so-well maintained **Nuvola 3.0**.x was available for free. The **entire source code** of Nuvola 3 & 4 is and always was available for free as well to make third-party builds possible.

Before the imminent end-of-life of Nuvola 3.0, **Nuvola 4.7** introduced a free trial and a $1/month subscription (Nuvola Basic). The intention was to provide users with an opportunity to try out basic features and then purchase Nuvola if they like it. Originally, the free trial was planned to be time-limited (as they almost always are), but the first implementation eventually didn’t include any time limit. I simply didn’t have time to add that as I focused on Chromium port of Nuvola.

The free trial widget was designed not to be annoying. It was only a narrow bar at the very bottom of the application window, one label and one purchase button. No random pop-up window, no screen overlays, no slide-in bars, no blinking, no yellow font on a red background, nothing like that. However, these banners are never liked in general. A widget asking for purchase should not be in the main window, or it is always annoying. I finally understand that.

Recent feedback on Twitter made me realize that users might find confusing that the trial is not time-limited. The author recommended “clarifying the wording of the nag banner to avoid user confusion”. He was correct. Since the time limit was not implemented, the wording of the widget became ill-conceived and confusing.

### Money-back guarantee

I’ve decided to discontinue the “free trial” instead because I don’t want Nuvola to be an app with “a nag banner”.  Widgets asking for a purchase are never popular. As a replacement, I now offer a N-day money-back guarantee to new purchases on Gumroad. You can ask for a refund of a new purchase within N days from the purchase and you will always get it. 

### Time Limit

I've decided to remove the trial bar from the main window (widgets asking for purchase are never popular) and implement a proper free trial this time. Upon installation, all features and locked and you can start a N-day free trial from the Preferences window to unlock Nuvola Basic features. When the trial expires, a purchase is required to keep the features unlocked. A purchase is always required to unlock Nuvola Premium features.

### Combined

I've decided to remove the trial bar from the main window  (widgets asking for purchase are never popular) and implement a proper free trial this time. Upon installation, all features and locked and you can start a N-day free trial from the Preferences window to unlock Nuvola Basic features. When the trial expires, a purchase is required to keep the features unlocked. A purchase is always required to unlock Nuvola Premium features, but I offer a N-day money-back guarantee, so you'll get your money back if you are not satisfied. You can ask for a refund of a new purchase within N days from the purchase and you will always get it.

**Comment by fenryxo** [comment]
I like the solution 3 most. A 30-day free trial & a 14-day money-back guarantee.

**Comment by locke99gs** [comment]
Many people don't like subscriptions and would rather purchase a product outright, even if it means limited support in the future. Would it be financially feasible to add a one-time purchase option, at like $49 or so to offer similar to the basic tier?

**Comment by fenryxo** [comment]
Hello @locke99gs. You can purchase a one-year subscription (for $12), cancel it right away and then enjoy one year of updates. Or would you like to prepaid 2/5 years as a one-time purchase?

**Comment by fenryxo** [comment]
Or would you prefer to purchase a single Nuvola release (e.g. Nuvola 4.10) to use it forever but without any future improvements, new features, and new scripts?

**Comment by locke99gs** [comment]
I'm OK with purchasing a subscription with a very long term, as a one time purchase. 
I am also OK with purchasing a version outright, but would still expect some basic level of support, like bug fixes. What about if a person bought into a major version, and received updates for that but now on new versions? For instance:
- One time purchase of version 4 for some reasonable amount of money 
- Receive all point upgrades to this version, forever.
- No expectation of support for this version when the next version is released
- Have to purchase again for version 5

**Comment by fenryxo** [comment]
> I'm OK with purchasing a subscription with a very long term, as a one time purchase.

What is "a very long term"?

> One time purchase of version 4 for some reasonable amount of money

What is "some reasonable amount of money"?

> No expectation of support for this version when the next version is released

Even if you purchase Nuvola 4 one day before Nuvola 5 is released?

> Have to purchase again for version 5

Well, there are no plans to release Nuvola 5 as Nuvola is steadily evolving with small changes. On the other hand, Nuvola 4.x may reach 4.14 by the end of 2018, so it would make sense to reset the counter to "X.0.0" once a year.

**Comment by fenryxo** [comment]
>> No expectation of support for this version when the next version is released

> Even if you purchase Nuvola 4 one day before Nuvola 5 is released?

How about selling a combined "Nuvola 4 & 5" license a few months before Nuvola 5 release?

**Comment by fenryxo** [comment]
Or this?
![selection_220](https://user-images.githubusercontent.com/853706/39822445-d8737f2e-53aa-11e8-9bee-2564e1086766.png)

**Comment by locke99gs** [comment]
@fenryxo 

> What is "a very long term"?
I feel many people (certainly not all) don't like the idea of a subscription, and prefer the feeling of ownership. I am one of these people - I tend to prefer to buy things rather than subscribing or leasing. I understand that a subscription allows recurring income for the developer, which is needed to keep the software current.

I would probably consider long term something like 2+ years.

> What is "some reasonable amount of money"?
I can't really answer that. I'm not afraid of spending money. How much you feel is reasonable and appropriate would have to be up to you. I do not know how much time or effort goes into developing this, nor do I know how much time and effort you intend to devote to it in the future.

> Even if you purchase Nuvola 4 one day before Nuvola 5 is released?
You're right; this could be a potential source of frustration.


I do like your proposed purchase options. Both provide a sense of ownership. While they cost more than the equivalent 1 year subscription, they allow continued use. I would feel comfortable purchasing one of either of those.

**Comment by hackel** [comment]
What exactly are you "guaranteeing?"  You better have those terms laid out explicitly and reviewed by a lawyer.  I, personally, wouldn't make any guarantees.  Your license explicitly excludes any "warranties."  IANAL, but a guarantee sounds awfully similar.  You can still offer people their money back.

You left out option 4: release the binaries just like the vast majority of open source software does, without charging, and let your backers continue to support you with donations and Patreon.  I personally do not get enough use out of the software that I would consider paying you to build it for me over simply using a web interface.  That's not your fault, though, just my own needs.  So going back to a trial-only model will most certainly cut off many of your users like me, but that's fine if you think it best.

> I feel many people (certainly not all) don't like the idea of a subscription, and prefer the feeling of ownership

@locke99gs No software is "owned."  People may not realize it, but they are never buying anything but a license to *use* it.  In this case, they are paying for a *service* (providing and hosting binary builds of the software), because they are already covered under the existing open-source license.

**Comment by fenryxo** [comment]
Thanks, @locke99gs, for your feedback.

> I feel many people (certainly not all) don't like the idea of a subscription, and prefer the feeling of ownership. I am one of these people - I tend to prefer to buy things rather than subscribing or leasing.

Thanks for explaining your point of view. I presumed users would choose the most cost-effective option, but the idea of ownership makes sense too.

> I do like your proposed purchase options. Both provide a sense of ownership. While they cost more than the equivalent 1 year subscription, they allow continued use. I would feel comfortable purchasing one of either of those.

I'll probably go with the Nuvola 4.x option first as a test.

---

Thanks, @hackel, for your feedback.

> What exactly are you "guaranteeing?" You better have those terms laid out explicitly and reviewed by a lawyer.

I agree it must be laid out explicitly. Basically, the 14-day money-back guarantee means that you can ask for a refund of a new purchase within 14 days from the purchase and you will always get it. When purchasing Nuvola, there are extra implied guarantees beyond the license of the source code, e.g. you get updates, new features and bug fixes during your subscription at no extra cost.

> You left out option 4: release the binaries just like the vast majority of open source software does, without charging, and let your backers continue to support you with donations and Patreon.

I don't want to beg for donations. I want to offer something extra to paying users - tested, supported & continuously updated official binary builds. Others can build Nuvola from the source code or use community builds - just like in the case of the vast majority of open source software.

> I personally do not get enough use out of the software that I would consider paying you to build it for me over simply using a web interface. That's not your fault, though, just my own needs.

Which features of Nuvola do you use? I mean what is your reason to use Nuvola instead of a regular web browser?

**Comment by pszi1ard** [comment]
I understand that you struggle with finding a sustainable monetization scheme, but I think you misunderstood the feedback you received. Specifically to your points:

> 1. Users don't like the idea of paying for Nuvola.
You are not a special case. Stable monetization has been a struggle in the OSS/free software community -- Canonical failed at it and Elementary is facing challenges too. The reasons are complex -- with a healthy dose of idiosyncrasies of free software tradition and the trends of free everything free on the web of today --, but it is definitely not because users "don't like the idea of" paying specifically for _your_ software.

> 2. Users don't like the trial widget, some calling it "a nag bar".
Blaming the users for ill-conceived and confusing messaging is a bad start. I'd rather recommend that you reflect on how was your UI/UX design and messaging confusing and why did it lead to such confusion and feedback.

> 3. Users are confused because the trial is not time-limited.
Same as above. Also, "trial software" has a fairly well-defined meaning, you need to _first_ figure out what kind of user-base you have / you want to have, what form of monetization is suitable for your needs _and_ acceptable for your users.

To sum it up: less IMHO confusing messaging, well thought-out and realistic monetization scheme, and preferably a good, decent knowledge of your user base and positive connection with them, especially if you want to make fundamental changes that push people around are essential prerequisites to the kind of changes you propose. Importantly, try to start out with less blame and more positive change. Additionally, preferably do know what _you_ want to accomplish with your software on the long run and implement changes with minimally invasive and offensive steps (improving on past practices). Annoying your users will unlikely to work, especially if you also ask them to pay at the same time.

Good luck with the changes!

PS:  have you considered working together with the Elementary guys and submitting to the App center. Might be a good experience in improving UI/UX and refining user messaging.

**Comment by fenryxo** [comment]
Thanks for your feedback, @pszi1ard. 

> [...] it is definitely not because users "don't like the idea of" paying specifically for your software.

I understand that but I intended to keep this ticked focused on Nuvola. "Users don't like the idea of paying for OSS, which includes paying for Nuvola." would be more precise.

>> 2. Users don't like the trial widget, some calling it "a nag bar".

> Blaming the users for ill-conceived and confusing messaging is a bad start. I'd rather recommend that you reflect on how was your UI/UX design and messaging confusing and why did it lead to such confusion and feedback.

First, this point is not actually about the content/wording but these banners in general. A similar bar in Nuvola 3, which asked for donations without any confusing wording, was neither favorite. A widget asking for purchase should not be in the main window, or it is always annoying.  

Second, I don't blame the users for that. I simply state that the fact that users don't like the widget is an issue to be solved.

>> 3. Users are confused because the trial is not time-limited.

> Same as above.

As above, I state that this is an issue to be solved, not that users should be blamed for the confusing text. I agree that the text is ill-conceived. Are only these two sentences what sound like I blame users or is there more? I've clarified the very first post. Is it more clear?

> To sum it up: less IMHO confusing messaging, well thought-out and realistic monetization scheme, and preferably a good, decent knowledge of your user base and positive connection with them, especially if you want to make fundamental changes that push people around are essential prerequisites to the kind of changes you propose. Importantly, try to start out with less blame and more positive change. Additionally, preferably do know what _you_ want to accomplish with your software on the long run and implement changes with minimally invasive and offensive steps (improving on past practices). Annoying your users will unlikely to work, especially if you also ask them to pay at the same time.

Thanks for your recommendation :-)

> PS: have you considered working together with the Elementary guys and submitting to the App center. Might be a good experience in improving UI/UX and refining user messaging.

I was excited about Elementary's App Center and I contributed to their fundraiser. Unfortunately, it was based on DEB packages, which was a no-go for Nuvola. The reliance on system libraries held Nuvola back for years.

**Comment by fenryxo** [comment]
The bar now says "Free Tier" instead of "Free Trial".

**Comment by maroc81** [comment]
For me, the free trial was great since I got to try it long enough to realize how much I would use it.  I had nuvola 3 on my desktop at home but only used it a few times a month.  When I switched jobs last year, I ended up needing to listen to music all day to focus in a noisy environment and nuvola 4 was great for that.

I didn't mind the nag bar since I got to use all the features and get used to the idea of subscribing.  I read the reasons why you were asking for a subscription and understood.  The costs were reasonable but the process to sign up was quite annoying.  There were several times I thought "can't I just send this guy $20 and not create all these accounts?"  Eventually I did create the accounts because it was worth it for how much I used it.

Now I use nuvola every day I'm at work.  This and wavebox are two applications I couldn't live without. I'm at a point now where I think quality software for Linux is worth paying for. The quality of nuvola and the documentation are top notch. Keep it coming!

**Comment by fenryxo** [comment]
Hello @maroc81. Thanks for your feedback.

> For me, the free trial was great since I got to try it long enough to realize how much I would use it.

The free tier will be preserved but only with a subset of Nuvola Basic features (e.g. MPRIS, background playback, media keys, Last.fm, lyrics). In addition, a time-limited free trial of Nuvola Premium will be introduced, which includes all features.

 > I didn't mind the nag bar since I got to use all the features and get used to the idea of subscribing.

Well, the problem with the nag bar is that spoils the very first user experience. That's always bad. 

> The costs were reasonable but the process to sign up was quite annoying. There were several times I thought "can't I just send this guy $20 and not create all these accounts?" Eventually I did create the accounts because it was worth it for how much I used it.

Indeed, the sign-up process needs to be improved. I've been thinking a lot about how to do that and work around the limitations of Gumroad API. I've been testing using license keys for one-time purchases (tiliado/nuvolaruntime#459) for a few months. You would purchase a lifetime license, get a license key to enter in Nuvola and that's it. No Tiliado account required. This should go live at the end of August. The next step is to do that for subscriptions (tiliado/nuvolaruntime#461), but that's a bit tricky.

> Now I use nuvola every day I'm at work. This and wavebox are two applications I couldn't live without. I'm at a point now where I think quality software for Linux is worth paying for. The quality of nuvola and the documentation are top notch. Keep it coming!

Glad to hear that you are so satisfied with Nuvola :-)

**Comment by fenryxo** [comment]
New in Nuvola 4.12.75 (75-g20af4ab):

* Trial bar was removed from the main window.
* 30-day free trial of Nuvola Premium was introduced.
* Nuvola switched to Gumroad license keys (#461), no Tiliado account is required for new purchases. Old purchases are still bound to a Tiliado account.
* Lifetime licenses (#459) are available (a one-time payment).

**Comment by fenryxo** [comment]
Announced in Update 10: [Nuvola Integrates Repeat & Shuffle Status, Adjusts to New Deezer Design, And More](https://medium.com/nuvola-news/nuvola-integrates-repeat-shuffle-status-adjusts-to-new-deezer-design-and-more-397d3bc1e03a)
