### ISSUE TITLE
Version mismatch: Nuvola Service != Nuvola Runtime

### ISSUE THREAD

**Issue by grechanyuk** [tiliado/nuvolaruntime#529]
I have this error in first window:
"Error message: Version mismatch: Nuvola Service 4.16.10 (10-gb11d0c4) != Nuvola Runtime 4.16.4 (4-g819cdb2)."
How to fix this?

**Comment by fenryxo** [comment]
Hello @grechanyuk. Nuvola Service flatpak package is newer than Nuvola Runtime of the streaming service you are about to use. The best way to solve the issue is to update all flatpaks.

- You can do it with a recent *GNOME Software/Ubuntu Software/KDE Discover* application (if the Flatpak plugin is installed).
- You can do it from the terminal: `flatpak update --user; flatpak update --system`

Does it help?

**Comment by grechanyuk** [comment]
Yes, thanks!

**Comment by fenryxo** [comment]
Great :-)
