### ISSUE TITLE
Update installation instructions for Ubuntu 20.04

### ISSUE THREAD

**Issue by kevin34ct** [tiliado/nuvolaruntime#607]
I just changed my os to Ubuntu 20.04 and it seems that flatpak will not install on my system.  There is a workaround by uninstalling the Snap store and installing Flatpak.  I was wondering if you might have a Snap version of the installer or maybe even a .deb install.  If not then I will try to convert to Flatpak but don't really like to change stores.

**Comment by fenryxo** [comment]
Hello @kevin34ct. Flatpak support was quite good in past Ubuntu releases. I wonder what has changed. Anyway, I'll look at it today/tomorrow. Thanks for reporting the issue :-)

**Comment by fenryxo** [comment]
Ubuntu switched to [a snap-packaged Software Store since Ubuntu 20.04 LTS](https://www.omgubuntu.co.uk/2020/02/ubuntu-snap-store-transition). While this step has many benefits, there is also one drawback: The snap version doesn't support Flatpak packages. If you wish to install Flatpak packages from a software store application, you need to install the original GNOME Software application.

Although both Ubuntu Software and GNOME Software may be installed on your system as independent applications, it might be confusing to have two applications with the same icons differing only in application name ("Ubuntu Software" for the snap version, "Software" for the original GNOME Software) and Flatpak support ("Software" supports Flatpak, "Ubuntu Software" doesn't). 

![focal_software_stores](https://user-images.githubusercontent.com/853706/81476711-9cbeb800-9213-11ea-93c4-fc320f1f1c8d.png)

If you find it unbearable, you may remove the snap version: `snap remove snap-store`.

The best solution would be to add Flatpak support to the snapped Ubuntu Software. It's very unfortunate that a long-term support release of Ubuntu contains a software center with reduced functionality.

Regarding Nuvola as snap/deb: While Nuvola 5 might be packaged also as a snap package, I have no interest in creating & maintaining deb packages.

**Comment by kevin34ct** [comment]
I was able to get it installed.  Flatpak is still installed, but not used
for the store.  I installed the service then installed one of the apps
which in turn installed Nuvola.  It's odd how it won't install Nuvola by
itself until an app is installed.  I'm using UbuntuDDE remix 20.04 but did
get it to work.  I just don't have a premium account anymore.

**Comment by fenryxo** [comment]
> I installed the service then installed one of the apps which in turn installed Nuvola. It's odd how it won't install Nuvola by itself until an app is installed.

I'm afraid I don't understand.

> I just don't have a premium account anymore.

I believe I replied to your support e-mail about that.

**Comment by kevin34ct** [comment]
The way to install on Ubuntu 20.04 is to install the app service then
install the app you want from the links on the install page.  Flathub is
already installed on 20.04.  Ubuntu 20.04 still uses Snap for software.
There is no need to install Flathub. I just thought you'd like to know so
it can be passed on to others.   That's my contribution since I don't know
how to program.  :)

The issue with my account is fixed, thank you.

Kevin Senecal

**Comment by fenryxo** [comment]
Hello @kevin34ct, I've added [detailed installation instructions for Ubuntu 20.04](https://nuvola.tiliado.eu/nuvola/ubuntu/focal/) based on our feedback. Could you review it?

> There is no need to install Flathub.

The minimal installation of Ubuntu 20.04 doesn't contain flatpak nor flathub. UbuntuDDE remix 20.04 might be different, but I need to provide more general instructions.

**Comment by kevin34ct** [comment]
Actually I  figured it out.  Flatpak is installed at the same time as Snap.

**Comment by fenryxo** [comment]
That seems strange. Anyway, instructions for general Ubuntu 20.04 seem correct.
