### ISSUE TITLE
Offline listening (Qobuz)

### ISSUE THREAD

**Issue by JoeKays** [tiliado/nuvolaruntime#627]
Hi,

I really enjoy the Qobuz app, but the missing offline listening feature really is a bummer. When I have an unstable connection I cannot listen at all...
Actually it's the only thing missing apart from maybe support for switching audio devices.

Thanks for making this, I will purchase a lifetime license in an instant if this feature is added!

**Comment by fenryxo** [comment]
Hello, @JoeKays. Nuvola uses Qobuz web player, which doesn't support offline listening - see [Is it possible to listen to music without internet connection?](https://help.qobuz.com/hc/en-us/articles/360026652411-Is-it-possible-to-listen-to-music-without-internet-connection-) Since Nuvola doesn't have direct access to the music, I cannot implement such a feature in Nuvola itself.
