### ISSUE TITLE
Automatically pause when headphones are unplugged [$5]

### ISSUE THREAD

**Issue by jwarkentin** [tiliado/nuvolaruntime#80]
# Feature Request

It would be very nice if there was an option (on by default?) to automatically pause the music when headphones get unplugged like what Android does. I use that intentionally on Android to pause my music quickly and easily. On my laptop it is frustrating for both me and those around me at work when I accidentally catch the headphone's cable and pull it out and the music starts blaring from the laptop's speakers. I would much rather have it auto-pause until I plug them back in.
# Implementation Notes
- [PreciseJackDetectionTesting](https://wiki.ubuntu.com/Audio/PreciseJackDetectionTesting) - PulseAudio seems to have headphones detection
##

**Comment by fenryxo** [comment]
Hi. Thanks for your idea how to make Nuvola Player better. I've added your feature request to [the wishlist](https://github.com/tiliado/nuvolaplayer/issues?q=is%3Aopen+label%3Awishlist+sort%3Acreated-asc). Since Nuvola Player project is currently underfunded, it can take a while before I process older feature requests and will start working on this issue. You can support your wish via [PayPal](https://tiliado.eu/nuvolaplayer/funding/#donate-wishlist) or [BountySource](https://www.bountysource.com/issues/9237193-automatically-pause-when-headphones-are-unplugged) to raise its priority though.

Jiří Janoušek, Nuvola Player Developer • *My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).*

**Comment by jwarkentin** [comment]
FYI, I have already been contributing to Nuvolaplayer weekly via Gratipay for over a year now :)

**Comment by fenryxo** [comment]
> FYI, I have already been contributing to Nuvolaplayer weekly via Gratipay for over a year now :)

Thanks for your support on Gratipay. However, [Gratipay donations are fully anonymous and come with no strings attached](https://gratipay.com/about/). It may change in the future though: gratipay/gratipay.com#236 and gratipay/gratipay.com#3112. I follow both tickets and will try to reach my Gratipay patrons as soon as it will be possible to break anonymity.

**Comment by fur0n** [comment]
Hello, I would like to add this to be worked on being implemented as part of my Patreon monthly pledge.

Thank You.

**Comment by fenryxo** [comment]
Hello @fur0n. Thanks for info. I've enqueued this ticket for next release.

**Comment by fenryxo** [comment]
WIP: https://github.com/tiliado/nuvolaruntime/tree/pulseaudio-tweaks

**Comment by fenryxo** [comment]
![pulseaudio_tweaks](https://user-images.githubusercontent.com/853706/37732326-01a9c72c-2d45-11e8-8d2a-a8f430b57390.png)

**Comment by fenryxo** [comment]
Available in Nuvola 4.10.8 (stable Flatpaks). @jwarkentin & @fur0n, could you test it?

**Comment by fur0n** [comment]
Yes, I was just able to test it and it is working for both unplugging and plugging the headphones in.

Thank You

**Comment by fenryxo** [comment]
:+1:
